version: '3.8'
services:
  mqtt-simulator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.simulator
    container_name: urbanmicrofarm-simulator
    environment:
      MQTT_BROKER: 20.240.208.122
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: simulator_device_001
      SENSOR_INTERVAL: 5
    restart: unless-stopped

  mqtt-ui:
    image: hivechat/mqtt-ui:latest
    container_name: urbanmicrofarm-mqtt-ui
    ports:
      - "8080:80"
    environment:
      MQTT_HOST: 20.240.208.122
      MQTT_PORT: 1883
networks:
  urbanmicrofarm-net:
    driver: bridge
